"""Khoi tao schema ban dau

Revision ID: 0d58347397a4
Revises: 
Create Date: 2026-08-26 10:33:05.228260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d58347397a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bo_phan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten')
    )
    op.create_table('bot_zalo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten', sa.String(length=100), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('webhook_secret', sa.String(length=64), nullable=True),
    sa.Column('dang_hoat_dong', sa.Boolean(), nullable=False),
    sa.Column('tao_luc', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten')
    )
    op.create_table('cai_dat',
    sa.Column('khoa', sa.String(length=50), nullable=False),
    sa.Column('gia_tri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('khoa')
    )
    op.create_table('chuc_vu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten', sa.String(length=100), nullable=False),
    sa.Column('mo_ta', sa.Text(), nullable=True),
    sa.Column('anh', sa.String(length=300), nullable=True),
    sa.Column('tao_luc', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten')
    )
    op.create_table('diem_cham_cong',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten', sa.String(length=150), nullable=False),
    sa.Column('dia_chi', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('ban_kinh_m', sa.Integer(), nullable=False),
    sa.Column('dang_hoat_dong', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nguoi_dung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_dinh_danh', sa.String(length=50), nullable=False),
    sa.Column('ho_ten', sa.String(length=120), nullable=False),
    sa.Column('mat_khau_hash', sa.String(length=255), nullable=False),
    sa.Column('vai_tro', sa.String(length=20), nullable=False),
    sa.Column('bo_phan_id', sa.Integer(), nullable=True),
    sa.Column('chuc_vu_id', sa.Integer(), nullable=True),
    sa.Column('so_dien_thoai', sa.String(length=20), nullable=True),
    sa.Column('zalo_group_id', sa.String(length=120), nullable=True),
    sa.Column('bot_zalo_id', sa.Integer(), nullable=True),
    sa.Column('dang_hoat_dong', sa.Boolean(), nullable=False),
    sa.Column('doi_mat_khau', sa.Boolean(), nullable=False),
    sa.Column('tao_luc', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bo_phan_id'], ['bo_phan.id'], ),
    sa.ForeignKeyConstraint(['bot_zalo_id'], ['bot_zalo.id'], ),
    sa.ForeignKeyConstraint(['chuc_vu_id'], ['chuc_vu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nguoi_dung', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nguoi_dung_ma_dinh_danh'), ['ma_dinh_danh'], unique=True)

    op.create_table('cham_cong',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nguoi_dung_id', sa.Integer(), nullable=False),
    sa.Column('ngay', sa.Date(), nullable=False),
    sa.Column('gio_vao', sa.DateTime(), nullable=True),
    sa.Column('lat_vao', sa.Float(), nullable=True),
    sa.Column('lng_vao', sa.Float(), nullable=True),
    sa.Column('do_chinh_xac_vao', sa.Float(), nullable=True),
    sa.Column('diem_vao_id', sa.Integer(), nullable=True),
    sa.Column('khoang_cach_vao', sa.Integer(), nullable=True),
    sa.Column('gio_ra', sa.DateTime(), nullable=True),
    sa.Column('lat_ra', sa.Float(), nullable=True),
    sa.Column('lng_ra', sa.Float(), nullable=True),
    sa.Column('do_chinh_xac_ra', sa.Float(), nullable=True),
    sa.Column('diem_ra_id', sa.Integer(), nullable=True),
    sa.Column('khoang_cach_ra', sa.Integer(), nullable=True),
    sa.Column('di_tre', sa.Boolean(), nullable=True),
    sa.Column('so_phut_tre', sa.Integer(), nullable=True),
    sa.Column('ve_som', sa.Boolean(), nullable=True),
    sa.Column('so_phut_som', sa.Integer(), nullable=True),
    sa.Column('nghi_khong_phep', sa.Boolean(), nullable=True),
    sa.Column('ip', sa.String(length=60), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('nghi_ngo', sa.Boolean(), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['diem_ra_id'], ['diem_cham_cong.id'], ),
    sa.ForeignKeyConstraint(['diem_vao_id'], ['diem_cham_cong.id'], ),
    sa.ForeignKeyConstraint(['nguoi_dung_id'], ['nguoi_dung.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nguoi_dung_id', 'ngay', name='uq_chamcong_ngay')
    )
    with op.batch_alter_table('cham_cong', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cham_cong_ngay'), ['ngay'], unique=False)
        batch_op.create_index(batch_op.f('ix_cham_cong_nguoi_dung_id'), ['nguoi_dung_id'], unique=False)

    op.create_table('cong_viec',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma', sa.String(length=20), nullable=True),
    sa.Column('tieu_de', sa.String(length=255), nullable=False),
    sa.Column('mo_ta', sa.Text(), nullable=True),
    sa.Column('nguoi_giao_id', sa.Integer(), nullable=False),
    sa.Column('nguoi_nhan_id', sa.Integer(), nullable=False),
    sa.Column('han', sa.DateTime(), nullable=True),
    sa.Column('do_uu_tien', sa.String(length=10), nullable=True),
    sa.Column('trang_thai', sa.String(length=20), nullable=False),
    sa.Column('lan_gui', sa.Integer(), nullable=False),
    sa.Column('tao_luc', sa.DateTime(), nullable=True),
    sa.Column('mo_lan_dau_luc', sa.DateTime(), nullable=True),
    sa.Column('gui_doi_chung_luc', sa.DateTime(), nullable=True),
    sa.Column('hoan_thanh_luc', sa.DateTime(), nullable=True),
    sa.Column('so_sao_cuoi', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nguoi_giao_id'], ['nguoi_dung.id'], ),
    sa.ForeignKeyConstraint(['nguoi_nhan_id'], ['nguoi_dung.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cong_viec', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cong_viec_han'), ['han'], unique=False)
        batch_op.create_index(batch_op.f('ix_cong_viec_hoan_thanh_luc'), ['hoan_thanh_luc'], unique=False)
        batch_op.create_index(batch_op.f('ix_cong_viec_ma'), ['ma'], unique=True)
        batch_op.create_index(batch_op.f('ix_cong_viec_nguoi_nhan_id'), ['nguoi_nhan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cong_viec_tao_luc'), ['tao_luc'], unique=False)
        batch_op.create_index(batch_op.f('ix_cong_viec_trang_thai'), ['trang_thai'], unique=False)

    op.create_table('xin_nghi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nguoi_dung_id', sa.Integer(), nullable=False),
    sa.Column('ngay', sa.Date(), nullable=False),
    sa.Column('buoi', sa.String(length=10), nullable=False),
    sa.Column('anh_minh_chung', sa.String(length=300), nullable=False),
    sa.Column('ghi_chu', sa.String(length=255), nullable=True),
    sa.Column('tao_luc', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nguoi_dung_id'], ['nguoi_dung.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nguoi_dung_id', 'ngay', 'buoi', name='uq_xinnghi_ngay_buoi')
    )
    with op.batch_alter_table('xin_nghi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_xin_nghi_ngay'), ['ngay'], unique=False)
        batch_op.create_index(batch_op.f('ix_xin_nghi_nguoi_dung_id'), ['nguoi_dung_id'], unique=False)

    op.create_table('danh_gia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cong_viec_id', sa.Integer(), nullable=False),
    sa.Column('nguoi_danh_gia_id', sa.Integer(), nullable=False),
    sa.Column('lan_gui', sa.Integer(), nullable=False),
    sa.Column('ket_qua', sa.String(length=20), nullable=False),
    sa.Column('so_sao', sa.Integer(), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('tao_luc', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cong_viec_id'], ['cong_viec.id'], ),
    sa.ForeignKeyConstraint(['nguoi_danh_gia_id'], ['nguoi_dung.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('danh_gia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_danh_gia_cong_viec_id'), ['cong_viec_id'], unique=False)

    op.create_table('dinh_kem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cong_viec_id', sa.Integer(), nullable=False),
    sa.Column('nguoi_tai_len_id', sa.Integer(), nullable=False),
    sa.Column('lan_gui', sa.Integer(), nullable=False),
    sa.Column('loai', sa.String(length=20), nullable=False),
    sa.Column('duong_dan', sa.String(length=300), nullable=False),
    sa.Column('ten_goc', sa.String(length=255), nullable=True),
    sa.Column('kich_thuoc', sa.Integer(), nullable=True),
    sa.Column('mime', sa.String(length=100), nullable=True),
    sa.Column('tao_luc', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cong_viec_id'], ['cong_viec.id'], ),
    sa.ForeignKeyConstraint(['nguoi_tai_len_id'], ['nguoi_dung.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dinh_kem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dinh_kem_cong_viec_id'), ['cong_viec_id'], unique=False)

    op.create_table('log_zalo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nguoi_dung_id', sa.Integer(), nullable=True),
    sa.Column('cong_viec_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.String(length=120), nullable=True),
    sa.Column('noi_dung', sa.Text(), nullable=True),
    sa.Column('thanh_cong', sa.Boolean(), nullable=True),
    sa.Column('phan_hoi', sa.Text(), nullable=True),
    sa.Column('tao_luc', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cong_viec_id'], ['cong_viec.id'], ),
    sa.ForeignKeyConstraint(['nguoi_dung_id'], ['nguoi_dung.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_zalo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_zalo_tao_luc'), ['tao_luc'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_zalo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_zalo_tao_luc'))

    op.drop_table('log_zalo')
    with op.batch_alter_table('dinh_kem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dinh_kem_cong_viec_id'))

    op.drop_table('dinh_kem')
    with op.batch_alter_table('danh_gia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_danh_gia_cong_viec_id'))

    op.drop_table('danh_gia')
    with op.batch_alter_table('xin_nghi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_xin_nghi_nguoi_dung_id'))
        batch_op.drop_index(batch_op.f('ix_xin_nghi_ngay'))

    op.drop_table('xin_nghi')
    with op.batch_alter_table('cong_viec', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cong_viec_trang_thai'))
        batch_op.drop_index(batch_op.f('ix_cong_viec_tao_luc'))
        batch_op.drop_index(batch_op.f('ix_cong_viec_nguoi_nhan_id'))
        batch_op.drop_index(batch_op.f('ix_cong_viec_ma'))
        batch_op.drop_index(batch_op.f('ix_cong_viec_hoan_thanh_luc'))
        batch_op.drop_index(batch_op.f('ix_cong_viec_han'))

    op.drop_table('cong_viec')
    with op.batch_alter_table('cham_cong', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cham_cong_nguoi_dung_id'))
        batch_op.drop_index(batch_op.f('ix_cham_cong_ngay'))

    op.drop_table('cham_cong')
    with op.batch_alter_table('nguoi_dung', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nguoi_dung_ma_dinh_danh'))

    op.drop_table('nguoi_dung')
    op.drop_table('diem_cham_cong')
    op.drop_table('chuc_vu')
    op.drop_table('cai_dat')
    op.drop_table('bot_zalo')
    op.drop_table('bo_phan')
    # ### end Alembic commands ###
