"""Them cot da_nhac_sap_qua_han

Revision ID: 71baf9e74579
Revises: 0d58347397a4
Create Date: 2026-08-26 17:02:41.633037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71baf9e74579'
down_revision = '0d58347397a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cong_viec', schema=None) as batch_op:
        batch_op.add_column(sa.Column('da_nhac_sap_qua_han', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cong_viec', schema=None) as batch_op:
        batch_op.drop_column('da_nhac_sap_qua_han')

    # ### end Alembic commands ###
