"""empty message

Revision ID: 899b58551b62
Revises: e94d5fbadc47
Create Date: 2026-08-27 19:00:06.648617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899b58551b62'
down_revision = 'e94d5fbadc47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ghi_chu_nop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cong_viec_id', sa.Integer(), nullable=False),
    sa.Column('lan_gui', sa.Integer(), nullable=False),
    sa.Column('noi_dung', sa.Text(), nullable=False),
    sa.Column('tao_luc', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cong_viec_id'], ['cong_viec.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cong_viec_id', 'lan_gui', name='uq_ghichunop_lan')
    )
    with op.batch_alter_table('ghi_chu_nop', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ghi_chu_nop_cong_viec_id'), ['cong_viec_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ghi_chu_nop', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ghi_chu_nop_cong_viec_id'))

    op.drop_table('ghi_chu_nop')
    # ### end Alembic commands ###
