"""empty message

Revision ID: 9b3bbc5fc962
Revises: 899b58551b62
Create Date: 2026-08-28 13:35:21.976947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3bbc5fc962'
down_revision = '899b58551b62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('san_pham_ai',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten', sa.String(length=255), nullable=False),
    sa.Column('mo_ta', sa.Text(), nullable=True),
    sa.Column('tao_luc', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anh_san_pham_ai',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('san_pham_id', sa.Integer(), nullable=False),
    sa.Column('duong_dan', sa.String(length=500), nullable=False),
    sa.Column('nhan', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['san_pham_id'], ['san_pham_ai.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anh_san_pham_ai', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anh_san_pham_ai_san_pham_id'), ['san_pham_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anh_san_pham_ai', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anh_san_pham_ai_san_pham_id'))

    op.drop_table('anh_san_pham_ai')
    op.drop_table('san_pham_ai')
    # ### end Alembic commands ###
