"""Tao bang goi_hang

Revision ID: a3b4c5d6e7f8
Revises: f6a7b8c9d0e1
Create Date: 2026-09-21 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b4c5d6e7f8'
down_revision = 'f6a7b8c9d0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'goi_hang',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ma_van_don', sa.String(length=50), nullable=False),
        sa.Column('nguoi_goi_id', sa.Integer(), nullable=False),
        sa.Column('duong_dan_anh', sa.String(length=300), nullable=False),
        sa.Column('ghi_chu', sa.String(length=255), nullable=True),
        sa.Column('tao_luc', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['nguoi_goi_id'], ['nguoi_dung.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('goi_hang', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goi_hang_ma_van_don'), ['ma_van_don'], unique=False)
        batch_op.create_index(batch_op.f('ix_goi_hang_nguoi_goi_id'), ['nguoi_goi_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goi_hang_tao_luc'), ['tao_luc'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goi_hang', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goi_hang_tao_luc'))
        batch_op.drop_index(batch_op.f('ix_goi_hang_nguoi_goi_id'))
        batch_op.drop_index(batch_op.f('ix_goi_hang_ma_van_don'))

    op.drop_table('goi_hang')

    # ### end Alembic commands ###
