"""Them cot ban_giao_cho_id cho xin_nghi

Revision ID: a7c9e2f4b1d3
Revises: da3aa1ada6eb
Create Date: 2026-08-28 18:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c9e2f4b1d3'
down_revision = 'da3aa1ada6eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xin_nghi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ban_giao_cho_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_xin_nghi_ban_giao_cho_id'), ['ban_giao_cho_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_xin_nghi_ban_giao_cho_id', 'nguoi_dung', ['ban_giao_cho_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xin_nghi', schema=None) as batch_op:
        batch_op.drop_constraint('fk_xin_nghi_ban_giao_cho_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_xin_nghi_ban_giao_cho_id'))
        batch_op.drop_column('ban_giao_cho_id')

    # ### end Alembic commands ###
