"""Tao bang anh_yeu_cau

Revision ID: b3d8f6a1c9e2
Revises: a7c9e2f4b1d3
Create Date: 2026-08-29 17:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d8f6a1c9e2'
down_revision = 'a7c9e2f4b1d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'anh_yeu_cau',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('cong_viec_id', sa.Integer(), nullable=False),
        sa.Column('duong_dan', sa.String(length=300), nullable=False),
        sa.Column('ten_goc', sa.String(length=255), nullable=True),
        sa.Column('tao_luc', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['cong_viec_id'], ['cong_viec.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('anh_yeu_cau', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anh_yeu_cau_cong_viec_id'), ['cong_viec_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anh_yeu_cau', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anh_yeu_cau_cong_viec_id'))
    op.drop_table('anh_yeu_cau')

    # ### end Alembic commands ###
