"""Tach anh goi_hang ra bang rieng (nhieu anh moi lan goi)

Revision ID: b4c5d6e7f8a9
Revises: a3b4c5d6e7f8
Create Date: 2026-09-21 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4c5d6e7f8a9'
down_revision = 'a3b4c5d6e7f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'anh_goi_hang',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('goi_hang_id', sa.Integer(), nullable=False),
        sa.Column('duong_dan', sa.String(length=300), nullable=False),
        sa.Column('tao_luc', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['goi_hang_id'], ['goi_hang.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('anh_goi_hang', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anh_goi_hang_goi_hang_id'), ['goi_hang_id'], unique=False)

    # Chuyển dữ liệu: nếu bảng goi_hang đã có bản ghi thật (migration
    # trước đã chạy trên VPS trước khi đổi model), copy ảnh cũ (1 ảnh/bản
    # ghi) sang bảng mới trước khi xoá cột duong_dan_anh — không mất dữ
    # liệu đã ghi nhận trước đó.
    conn = op.get_bind()
    goi_hang = sa.table('goi_hang', sa.column('id', sa.Integer), sa.column('duong_dan_anh', sa.String))
    anh_goi_hang = sa.table('anh_goi_hang', sa.column('goi_hang_id', sa.Integer), sa.column('duong_dan', sa.String))
    for hang in conn.execute(sa.select(goi_hang.c.id, goi_hang.c.duong_dan_anh)):
        if hang.duong_dan_anh:
            conn.execute(anh_goi_hang.insert().values(goi_hang_id=hang.id, duong_dan=hang.duong_dan_anh))

    with op.batch_alter_table('goi_hang', schema=None) as batch_op:
        batch_op.drop_column('duong_dan_anh')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goi_hang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duong_dan_anh', sa.String(length=300), nullable=True))

    conn = op.get_bind()
    goi_hang = sa.table('goi_hang', sa.column('id', sa.Integer), sa.column('duong_dan_anh', sa.String))
    anh_goi_hang = sa.table('anh_goi_hang', sa.column('id', sa.Integer),
                             sa.column('goi_hang_id', sa.Integer), sa.column('duong_dan', sa.String))
    # Downgrade chỉ giữ lại ẢNH ĐẦU TIÊN của mỗi lần gói (cột cũ chỉ chứa
    # được 1 ảnh) — các ảnh phụ sẽ mất khi hạ cấp, chấp nhận được vì
    # downgrade chỉ dùng khi cần lùi khẩn cấp, không phải luồng bình thường.
    da_gan = set()
    for a in conn.execute(sa.select(anh_goi_hang.c.goi_hang_id, anh_goi_hang.c.duong_dan).order_by(anh_goi_hang.c.id)):
        if a.goi_hang_id in da_gan:
            continue
        da_gan.add(a.goi_hang_id)
        conn.execute(goi_hang.update().where(goi_hang.c.id == a.goi_hang_id).values(duong_dan_anh=a.duong_dan))

    with op.batch_alter_table('anh_goi_hang', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anh_goi_hang_goi_hang_id'))

    op.drop_table('anh_goi_hang')

    # ### end Alembic commands ###
