"""empty message

Revision ID: b620692f8c4d
Revises: 9b3bbc5fc962
Create Date: 2026-08-28 15:06:55.317797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b620692f8c4d'
down_revision = '9b3bbc5fc962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tro_ly_su_dung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nguoi_dung_id', sa.Integer(), nullable=False),
    sa.Column('ngay', sa.Date(), nullable=False),
    sa.Column('so_cau_hoi', sa.Integer(), nullable=False),
    sa.Column('so_token', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nguoi_dung_id'], ['nguoi_dung.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nguoi_dung_id', 'ngay', name='uq_trolysudung_nguoi_ngay')
    )
    with op.batch_alter_table('tro_ly_su_dung', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tro_ly_su_dung_ngay'), ['ngay'], unique=False)
        batch_op.create_index(batch_op.f('ix_tro_ly_su_dung_nguoi_dung_id'), ['nguoi_dung_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tro_ly_su_dung', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tro_ly_su_dung_nguoi_dung_id'))
        batch_op.drop_index(batch_op.f('ix_tro_ly_su_dung_ngay'))

    op.drop_table('tro_ly_su_dung')
    # ### end Alembic commands ###
