"""Tao bang ngay_nghi_le

Revision ID: c4e7a9d2f5b1
Revises: b3d8f6a1c9e2
Create Date: 2026-08-31 09:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e7a9d2f5b1'
down_revision = 'b3d8f6a1c9e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'ngay_nghi_le',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('ngay', sa.Date(), nullable=False),
        sa.Column('ten', sa.String(length=255), nullable=False),
        sa.Column('tao_luc', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('ngay'),
    )
    with op.batch_alter_table('ngay_nghi_le', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ngay_nghi_le_ngay'), ['ngay'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ngay_nghi_le', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ngay_nghi_le_ngay'))
    op.drop_table('ngay_nghi_le')

    # ### end Alembic commands ###
