"""Doi goi_hang.ghi_chu thanh noi_dung (Text) - noi dung hang tu OCR

Revision ID: c5d6e7f8a9b0
Revises: b4c5d6e7f8a9
Create Date: 2026-09-21 15:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d6e7f8a9b0'
down_revision = 'b4c5d6e7f8a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goi_hang', schema=None) as batch_op:
        batch_op.alter_column(
            'ghi_chu', new_column_name='noi_dung',
            existing_type=sa.String(length=255), type_=sa.Text(), existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goi_hang', schema=None) as batch_op:
        batch_op.alter_column(
            'noi_dung', new_column_name='ghi_chu',
            existing_type=sa.Text(), type_=sa.String(length=255), existing_nullable=True,
        )

    # ### end Alembic commands ###
