"""Tao bang thong_bao

Revision ID: d4e5f6a7b8c9
Revises: f1a2b3c4d5e6
Create Date: 2026-09-03 09:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e5f6a7b8c9'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'thong_bao',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('noi_dung', sa.Text(), nullable=False),
        sa.Column('nguoi_dang_id', sa.Integer(), nullable=False),
        sa.Column('so_nguoi_nhan', sa.Integer(), nullable=True),
        sa.Column('tao_luc', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['nguoi_dang_id'], ['nguoi_dung.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thong_bao')

    # ### end Alembic commands ###
