"""empty message

Revision ID: da3aa1ada6eb
Revises: b620692f8c4d
Create Date: 2026-08-28 20:02:43.756341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da3aa1ada6eb'
down_revision = 'b620692f8c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anh_danh_gia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('danh_gia_id', sa.Integer(), nullable=False),
    sa.Column('duong_dan', sa.String(length=300), nullable=False),
    sa.Column('ten_goc', sa.String(length=255), nullable=True),
    sa.Column('tao_luc', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['danh_gia_id'], ['danh_gia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anh_danh_gia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anh_danh_gia_danh_gia_id'), ['danh_gia_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anh_danh_gia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anh_danh_gia_danh_gia_id'))

    op.drop_table('anh_danh_gia')
    # ### end Alembic commands ###
