"""Tao bang de_xuat

Revision ID: e5f6a7b8c9d0
Revises: d4e5f6a7b8c9
Create Date: 2026-09-04 09:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f6a7b8c9d0'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'de_xuat',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('loai', sa.String(length=20), nullable=False),
        sa.Column('nguoi_de_xuat_id', sa.Integer(), nullable=False),
        sa.Column('noi_dung', sa.Text(), nullable=False),
        sa.Column('chi_phi_du_kien', sa.Numeric(precision=14, scale=0), nullable=True),
        sa.Column('duong_dan_chu_ky_de_xuat', sa.String(length=300), nullable=False),
        sa.Column('duong_dan_pdf', sa.String(length=300), nullable=False),
        sa.Column('trang_thai', sa.String(length=20), nullable=False),
        sa.Column('nguoi_duyet_id', sa.Integer(), nullable=True),
        sa.Column('y_kien_duyet', sa.Text(), nullable=True),
        sa.Column('duong_dan_chu_ky_duyet', sa.String(length=300), nullable=True),
        sa.Column('duyet_luc', sa.DateTime(), nullable=True),
        sa.Column('tao_luc', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['nguoi_de_xuat_id'], ['nguoi_dung.id'], ),
        sa.ForeignKeyConstraint(['nguoi_duyet_id'], ['nguoi_dung.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('de_xuat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_de_xuat_nguoi_de_xuat_id'), ['nguoi_de_xuat_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('de_xuat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_de_xuat_nguoi_de_xuat_id'))

    op.drop_table('de_xuat')

    # ### end Alembic commands ###
