"""Them cot ngay_bat_dau cho cong viec

Revision ID: e94d5fbadc47
Revises: 71baf9e74579
Create Date: 2026-08-27 10:40:48.697747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e94d5fbadc47'
down_revision = '71baf9e74579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cong_viec', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ngay_bat_dau', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cong_viec', schema=None) as batch_op:
        batch_op.drop_column('ngay_bat_dau')

    # ### end Alembic commands ###
