"""Them cot link_moi, owner cho bot_zalo

Revision ID: f1a2b3c4d5e6
Revises: c4e7a9d2f5b1
Create Date: 2026-08-31 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a2b3c4d5e6'
down_revision = 'c4e7a9d2f5b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_zalo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_moi', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('owner', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_zalo', schema=None) as batch_op:
        batch_op.drop_column('owner')
        batch_op.drop_column('link_moi')

    # ### end Alembic commands ###
