"""Tao bang dinh_kem_de_xuat

Revision ID: f6a7b8c9d0e1
Revises: e5f6a7b8c9d0
Create Date: 2026-09-19 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a7b8c9d0e1'
down_revision = 'e5f6a7b8c9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'dinh_kem_de_xuat',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('de_xuat_id', sa.Integer(), nullable=False),
        sa.Column('giai_doan', sa.String(length=20), nullable=False),
        sa.Column('nguoi_tai_len_id', sa.Integer(), nullable=False),
        sa.Column('loai', sa.String(length=20), nullable=False),
        sa.Column('duong_dan', sa.String(length=300), nullable=False),
        sa.Column('ten_goc', sa.String(length=255), nullable=True),
        sa.Column('kich_thuoc', sa.Integer(), nullable=True),
        sa.Column('mime', sa.String(length=100), nullable=True),
        sa.Column('tao_luc', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['de_xuat_id'], ['de_xuat.id'], ),
        sa.ForeignKeyConstraint(['nguoi_tai_len_id'], ['nguoi_dung.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('dinh_kem_de_xuat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dinh_kem_de_xuat_de_xuat_id'), ['de_xuat_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dinh_kem_de_xuat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dinh_kem_de_xuat_de_xuat_id'))

    op.drop_table('dinh_kem_de_xuat')

    # ### end Alembic commands ###
